#!/usr/bin/env bash
# bash script to kills 7-highlander process
# Find the PID of the process
id=$(pgrep -f './7-highlander')

if [ -n "$id" ]; then
    # Send SIGKILL signal to terminate the process
    kill -s SIGKILL "$id"
    echo "Process terminated successfully."
else
    echo "Process not found or already terminated."
fi

