#!/usr/bin/env bash
# bash script to groups visitors by IP and HTTP status code and displays this data
# Use awk to count occurrences of each combination of IP and HTTP status code,
# then sort the data based on the occurrence number
awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' apache-access.log | sort -rn

